version: "3.8"

services:
  app:
    container_name: app
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
